export enum ROUTE {
  HOME = "/",
  MOVIE = "movie/:imdbID",
  FAVOURITE_MOVIE = "favourites/movie/:imdbID",
  TRENDING_MOVIE = "trends/movie/:imdbID",
  TRENDS = "trends",
  FAVOURITES = "favourites",
  SETTINGS = "settings",
  SIGN_IN = "sign-in",
  SIGN_UP = "sign-up",
  RESET_PASSWORD = "reset-password",
  CONTACTS = "contacts",
  ABOUT_US = "about",
  ORDERS = "orders",
}
